image: "docker.io/redoxos/redoxer"

stages:
    - build
    - test

cache:
    paths:
        - target/

build:redox:
    stage: build
    script: redoxer build --verbose

test:redox:
    stage: test
    dependencies:
        - build:redox
    script: redoxer test --verbose

build:linux:
    stage: build
    image: docker.io/library/rust:alpine
    script:
        - apk add musl-dev
        - cargo build --verbose

test:linux:
    stage: test
    image: docker.io/library/rust:alpine
    dependencies:
        - build:linux
    script: cargo test --verbose